### ISSUE TITLE
Problem running docs locally

### ISSUE THREAD

**Issue by harrisondnash** [influxdata/docs-v2#1875]
When trying to run Docs locally I encountered this error:
```
Start building sites … 
ERROR 2020/11/20 17:59:23 POSTCSS: failed to transform "dark-theme.css" (text/css): /usr/local/lib/node_modules/postcss-cli/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/postcss-cli/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
ERROR 2020/11/20 17:59:23 POSTCSS: failed to transform "dark-theme.css" (text/css): /usr/local/lib/node_modules/postcss-cli/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/postcss-cli/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
ERROR 2020/11/20 17:59:23 POSTCSS: failed to transform "light-theme.css" (text/css): /usr/local/lib/node_modules/postcss-cli/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/postcss-cli/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
ERROR 2020/11/20 17:59:23 POSTCSS: failed to transform "api.css" (text/css): /usr/local/lib/node_modules/postcss-cli/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/postcss-cli/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
Built in 33554 ms
Error: Error building site: POSTCSS: failed to transform "light-theme.css" (text/css): /usr/local/lib/node_modules/postcss-cli/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/postcss-cli/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```

##### Relevant URLs
https://github.com/influxdata/docs-v2/blob/master/README.md

##### What products and version are you using?

Mac OS 10.14
Hugo v0.78.2
npm 5.6.0

**Comment by sanderson** [comment]
@harrisondnash The docs are currently only tested with up to Hugo 0.75. Can you downgrade Hugo and attempt to run the docs again?

**Comment by harrisondnash** [comment]
I downgraded to v0.75 I am still getting an error
```
ERROR 2020/11/24 19:49:18 TOCSS: failed to transform "styles/styles-dark.scss" (text/x-scss): resource "scss/styles/styles-dark.scss_f4320040a399b68ce06274b21a585702" not found in file cache
```
Should I downgrade to an even earlier version? Thank you.

**Comment by sanderson** [comment]
@harrisondnash you installed all the dependencies?

```
npm i -g postcss-cli autoprefixer
```

**Comment by sanderson** [comment]
Closing this issue for now. If you are still unable to run the docs, feel free to reopen.

**Comment by harrisondnash** [comment]
Hello @sanderson, 
Thank you for your help. I've tried installing the dependencies as well as installing extended versions of both 0.75 and 0.68.3. I still get 
```
2020/12/16 16:29:23 POSTCSS: failed to transform "dark-theme.css" (text/css): /usr/local/lib/node_modules/postcss-cli/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/postcss-cli/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
```
Any thoughts?
